import { CONTROL_IDS, isKnownControl } from "./control-catalog.mjs";

export const EVIDENCE_ARTIFACTS = Object.freeze({
  ACCESS_REVIEW_EXPORT: "evidence/access-review-export.json",
  OWNER_REGISTRY_EXPORT: "evidence/owner-registry.csv",
  RESIDENCY_CONFIG_EXPORT: "evidence/residency-config.json",
  RETENTION_POLICY_EXPORT: "evidence/retention-policy.yaml",
  AUDIT_LOG_EXPORT: "evidence/audit-log.ndjson",
  APPROVAL_DECISION_LOG: "evidence/approval-decisions.ndjson",
  RAI_ASSESSMENT_REPORT: "evidence/rai-assessment.md",
  RBAC_ASSIGNMENT_REVIEW: "evidence/rbac-assignment-review.csv",
  BYO_ENTRA_ONBOARDING_PACKAGE: "evidence/byo-entra-onboarding.md",
  KEYVAULT_ROTATION_PLAN: "evidence/keyvault-rotation-plan.json",
  TENANT_ONBOARDING_BUNDLE: "evidence/tenant-onboarding-bundle.json",
  TENANT_RESOURCE_TEMPLATE: "evidence/tenant-resource-template.json",
  TENANT_ONBOARDING_SCRIPT_PACK: "evidence/tenant-onboarding-scripts.json",
  POLICY_CATALOG_EXPORT: "evidence/policy-catalog.json",
  CI_CD_VALIDATION_REPORT: "evidence/cicd-validation-report.json",
  PURVIEW_LABEL_EXPORT: "evidence/purview-label-export.csv",
  PII_DETECTION_FINDINGS: "evidence/pii-detection-findings.ndjson",
  OVERSHARE_INCIDENT_LOG: "evidence/overshare-incidents.ndjson",
  OVERSHARE_ENFORCEMENT_DECISIONS: "evidence/overshare-enforcement-decisions.ndjson",
  SIEM_CONNECTOR_CONFIG: "evidence/siem-connector-config.json",
  SIEM_ALERT_ROUTING: "evidence/siem-alert-routing.json",
  INCIDENT_PLAYBOOK_CATALOG: "evidence/incident-playbooks.json",
  CONSENT_DASHBOARD_EXPORT: "evidence/consent-dashboard.json",
  REGIONAL_STORAGE_PLAN: "evidence/regional-storage-plan.json",
  DELETION_WORKFLOW_EXPORT: "evidence/deletion-workflow.yaml",
});

const DEFAULT_EVIDENCE_MAPPING = Object.freeze({
  [CONTROL_IDS.ACCESS_LEAST_PRIVILEGE]: [
    EVIDENCE_ARTIFACTS.ACCESS_REVIEW_EXPORT,
    EVIDENCE_ARTIFACTS.AUDIT_LOG_EXPORT,
  ],
  [CONTROL_IDS.ACCESS_OWNER_ACCOUNTABILITY]: [EVIDENCE_ARTIFACTS.OWNER_REGISTRY_EXPORT],
  [CONTROL_IDS.DATA_RETENTION_POLICY]: [EVIDENCE_ARTIFACTS.RETENTION_POLICY_EXPORT],
  [CONTROL_IDS.AUDIT_TRACEABILITY]: [
    EVIDENCE_ARTIFACTS.AUDIT_LOG_EXPORT,
    EVIDENCE_ARTIFACTS.OVERSHARE_ENFORCEMENT_DECISIONS,
    EVIDENCE_ARTIFACTS.SIEM_CONNECTOR_CONFIG,
    EVIDENCE_ARTIFACTS.SIEM_ALERT_ROUTING,
    EVIDENCE_ARTIFACTS.INCIDENT_PLAYBOOK_CATALOG,
  ],
  [CONTROL_IDS.APPROVAL_GATES]: [EVIDENCE_ARTIFACTS.APPROVAL_DECISION_LOG],
  [CONTROL_IDS.RESPONSIBLE_AI_REVIEW]: [EVIDENCE_ARTIFACTS.RAI_ASSESSMENT_REPORT],
  [CONTROL_IDS.RBAC_ROLE_SEGREGATION]: [EVIDENCE_ARTIFACTS.RBAC_ASSIGNMENT_REVIEW],
  [CONTROL_IDS.BYO_ENTRA_ONBOARDING]: [
    EVIDENCE_ARTIFACTS.BYO_ENTRA_ONBOARDING_PACKAGE,
    EVIDENCE_ARTIFACTS.TENANT_ONBOARDING_BUNDLE,
    EVIDENCE_ARTIFACTS.TENANT_ONBOARDING_SCRIPT_PACK,
  ],
  [CONTROL_IDS.SECRET_ROTATION]: [EVIDENCE_ARTIFACTS.KEYVAULT_ROTATION_PLAN],
  [CONTROL_IDS.DATA_RESIDENCY_ENFORCEMENT]: [
    EVIDENCE_ARTIFACTS.RESIDENCY_CONFIG_EXPORT,
    EVIDENCE_ARTIFACTS.TENANT_RESOURCE_TEMPLATE,
  ],
  [CONTROL_IDS.POLICY_AS_CODE_ENFORCEMENT]: [EVIDENCE_ARTIFACTS.POLICY_CATALOG_EXPORT],
  [CONTROL_IDS.CI_CD_VALIDATION_GATES]: [EVIDENCE_ARTIFACTS.CI_CD_VALIDATION_REPORT],
  [CONTROL_IDS.PURVIEW_LABEL_ENFORCEMENT]: [
    EVIDENCE_ARTIFACTS.PURVIEW_LABEL_EXPORT,
    EVIDENCE_ARTIFACTS.OVERSHARE_INCIDENT_LOG,
  ],
  [CONTROL_IDS.PII_DETECTION_REDACTION]: [
    EVIDENCE_ARTIFACTS.PII_DETECTION_FINDINGS,
    EVIDENCE_ARTIFACTS.OVERSHARE_INCIDENT_LOG,
  ],
  [CONTROL_IDS.CONSENT_PRIVACY_NOTICE]: [EVIDENCE_ARTIFACTS.CONSENT_DASHBOARD_EXPORT],
  [CONTROL_IDS.REGIONAL_STORAGE_ALIGNMENT]: [
    EVIDENCE_ARTIFACTS.REGIONAL_STORAGE_PLAN,
    EVIDENCE_ARTIFACTS.TENANT_RESOURCE_TEMPLATE,
  ],
  [CONTROL_IDS.DATA_DELETION_WORKFLOW]: [EVIDENCE_ARTIFACTS.DELETION_WORKFLOW_EXPORT],
});

/**
 * @param {string} controlId
 */
export function getEvidenceArtifactsForControl(controlId) {
  if (!isKnownControl(controlId)) return [];
  return DEFAULT_EVIDENCE_MAPPING[controlId] ?? [];
}

export function getEvidenceMapping() {
  return DEFAULT_EVIDENCE_MAPPING;
}
